FROM node:22-alpine

WORKDIR /app

COPY ./Backend/package*.json .
COPY ./Backend/tsconfig.json ./tsconfig.json
COPY ./Backend/source ./source
COPY ./Backend/source/views ./source/views
COPY ./Backend/public ./public
COPY ./Backend/uploads ./uploads

RUN npm install
RUN npm run build

CMD ["npm", "run", "start"]
