FROM node:18-alpine

WORKDIR /app

COPY ./frontend/package*.json .
COPY ./frontend/README.md .
COPY ./frontend/public ./public
COPY ./frontend/src ./src

RUN npm install
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
