services:
  activa-db:
    image: mysql:8.0
    container_name: activa-db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - activa-db-data:/var/lib/mysql   
      - ./gimnasio_activa.sql:/docker-entrypoint-initdb.d/gimnasio_activa.sql
    ports:
      - "3307:3306"

  activa-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: activa-backend-container
    env_file: ./Backend/.env
    restart: always
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER_CONECT: ${DATABASE_USER}
      DATABASE_PASSWORD_CONECT: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      NODE_ENV : ${NODE_ENV}
    ports:
      - "3032:3032"
    depends_on:
      - activa-db

  activa-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: activa-frontend-container
    env_file: ./frontend/.env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - activa-db

  activa-ngnix:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: activa-nginx-container
    restart: always
    ports:
      # puerto http 
      - "80:80"
      # puerto https
      # - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx

volumes:
  activa-db-data:
