services:
  activa-db:
    image: mysql:8.0
    container_name: activa-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - activa-db-data:/var/lib/mysql
      - ./mysqldump-backup.sh:/usr/local/bin/mysqldump-backup.sh
    ports:
      - "3307:3306"

  activa-backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: activa-backend
    env_file: ./Backend/.env
    restart: always
    ports:
      - "3032:3032"
    depends_on:
      - activa-db

  activa-nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: activa-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - activa-backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx

volumes:
  activa-db-data:
