server {
    # *.activa.gniglio.com.ar
    server_name activafitness.com.ar;
    listen 80;

    location / {
        proxy_pass http://activa-backend:3032/;
        # proxy_pass http://activa-backend:3032;
        # WebSocket  protocolo que permite establecer una conexión permanente y bidireccional
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
    # listen 443 ssl; # managed by Certbot
    # ssl_certificate /etc/letsencrypt/live/dashboard.activa.gniglio.com.ar/fullchain.pem; # managed by Certbot
    # ssl_certificate_key /etc/letsencrypt/live/dashboard.activa.gniglio.com.ar/privkey.pem; # managed by Certbot
    # include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbotsss
}

server{
    server_name dashboard.activa.gniglio.com.ar;
    listen 80;

    location / {
        proxy_pass http://activa-flask:5000/;

        # proxy_pass http://activa-frontend:3000/;
        # WebSocket protocolo que permite establecer una conexión permanente y bidireccional
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dashboard.activa.gniglio.com.ar/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dashboard.activa.gniglio.com.ar/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbotsss
}

server {
    # *.activa.gniglio.com.ar
    server_name fitness.activa.gniglio.com.ar;
    listen 80;

    location / {
        proxy_pass http://activa-backend:3032/;
        # proxy_pass http://activa-backend:3032;
        # WebSocket  protocolo que permite establecer una conexión permanente y bidireccional
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dashboard.activa.gniglio.com.ar/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dashboard.activa.gniglio.com.ar/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbotsss
}

server{
    server_name dashboard.activa.gniglio.com.ar;
    listen 80;

    location / {
        proxy_pass http://activa-flask:5000/;

        # proxy_pass http://activa-frontend:3000/;
        # WebSocket protocolo que permite establecer una conexión permanente y bidireccional
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dashboard.activa.gniglio.com.ar/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dashboard.activa.gniglio.com.ar/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbotsss
}
