server {
    server_name activa.fitness;
    listen 80;

    location / {
        proxy_pass http://localhost:3032;
        # WebSocket  protocolo que permite establecer una conexión permanente y bidireccional
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }

    location /admin/ {
        proxy_pass http://localhost:3000/;
        # WebSocket protocolo que permite establecer una conexión permanente y bidireccional
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }


    #  listen 443 ssl; # managed by Certbot
    # ssl_certificate /etc/letsencrypt/live/adm.gim.gniglio.com.ar/fullchain.pem; # managed by Certbot
    # ssl_certificate_key /etc/letsencrypt/live/adm.gim.gniglio.com.ar/privkey.pem; # managed by Certbot
    # include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    # ssl  _dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbotsss
}
